POST http://127.0.0.1:8080/api/auth/login
content-type: application/json

{   
    "email": "test@test.test6",
    "name": "sample",
    "password": "testPassword"
}

###



POST http://127.0.0.1:8080/api/user/register
content-type: application/json

{   
    "email": "test@test.test6",
    "name": "sample",
    "password": "testPassword"
}

###

POST http://127.0.0.1:8080/api/ticket/create
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsInJvbGUiOiJtZW1iZXIiLCJpc3MiOiJ0ZXN0IiwiZXhwIjoxNzcyODAxNzkzLCJpYXQiOjE3NzI4MDE3Njl9.x8EplruU1r4qY-9kgeF2WERBppPwRwlCx03IWTkGzB4

{
    "email": "test@test.test",
    "name": "sample",
    "password": "testPassword"
}

###