// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: booking_items.sql

package sqlc_repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBookingItem = `-- name: CreateBookingItem :one
INSERT INTO booking_items (booking_id, ticket_type_id, quantity, price_at_booking)
VALUES ($1, $2, $3, $4)
RETURNING id, booking_id, ticket_type_id, quantity, price_at_booking
`

type CreateBookingItemParams struct {
	BookingID      int64          `json:"booking_id"`
	TicketTypeID   int64          `json:"ticket_type_id"`
	Quantity       int32          `json:"quantity"`
	PriceAtBooking pgtype.Numeric `json:"price_at_booking"`
}

func (q *Queries) CreateBookingItem(ctx context.Context, arg CreateBookingItemParams) (BookingItem, error) {
	row := q.db.QueryRow(ctx, createBookingItem,
		arg.BookingID,
		arg.TicketTypeID,
		arg.Quantity,
		arg.PriceAtBooking,
	)
	var i BookingItem
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.TicketTypeID,
		&i.Quantity,
		&i.PriceAtBooking,
	)
	return i, err
}

const getAllBookingItems = `-- name: GetAllBookingItems :many
SELECT id, booking_id, ticket_type_id, quantity, price_at_booking FROM booking_items
`

func (q *Queries) GetAllBookingItems(ctx context.Context) ([]BookingItem, error) {
	rows, err := q.db.Query(ctx, getAllBookingItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingItem
	for rows.Next() {
		var i BookingItem
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.TicketTypeID,
			&i.Quantity,
			&i.PriceAtBooking,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingItem = `-- name: GetBookingItem :one
SELECT booking_items.id, booking_items.booking_id, booking_items.ticket_type_id, booking_items.quantity, booking_items.price_at_booking, booking.id, booking.account_id, booking.status, booking.expires_at, booking.paid_at, booking.created_at, ticket_type.id, ticket_type.name, ticket_type.description, ticket_type.price, ticket_type.available_quantity, ticket_type.event_id, ticket_type.created_at
FROM booking_items
JOIN booking ON booking.id == booking_items.booking_id
JOIN ticket_type ON ticket_type.id == booking_items.ticket_type_id
WHERE booking_items.id = $1
`

type GetBookingItemRow struct {
	BookingItem BookingItem `json:"booking_item"`
	Booking     Booking     `json:"booking"`
	TicketType  TicketType  `json:"ticket_type"`
}

func (q *Queries) GetBookingItem(ctx context.Context, id int64) (GetBookingItemRow, error) {
	row := q.db.QueryRow(ctx, getBookingItem, id)
	var i GetBookingItemRow
	err := row.Scan(
		&i.BookingItem.ID,
		&i.BookingItem.BookingID,
		&i.BookingItem.TicketTypeID,
		&i.BookingItem.Quantity,
		&i.BookingItem.PriceAtBooking,
		&i.Booking.ID,
		&i.Booking.AccountID,
		&i.Booking.Status,
		&i.Booking.ExpiresAt,
		&i.Booking.PaidAt,
		&i.Booking.CreatedAt,
		&i.TicketType.ID,
		&i.TicketType.Name,
		&i.TicketType.Description,
		&i.TicketType.Price,
		&i.TicketType.AvailableQuantity,
		&i.TicketType.EventID,
		&i.TicketType.CreatedAt,
	)
	return i, err
}
