// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: booking.sql

package sqlc_repository

import (
	"context"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO booking (account_id, event_id, quantity)
VALUES ($1, $2, $3)
RETURNING id, account_id, event_id, quantity
`

type CreateBookingParams struct {
	AccountID int64 `json:"account_id"`
	EventID   int64 `json:"event_id"`
	Quantity  int32 `json:"quantity"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking, arg.AccountID, arg.EventID, arg.Quantity)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.EventID,
		&i.Quantity,
	)
	return i, err
}

const getAllBookings = `-- name: GetAllBookings :many
SELECT id, account_id, event_id, quantity FROM booking
`

func (q *Queries) GetAllBookings(ctx context.Context) ([]Booking, error) {
	rows, err := q.db.Query(ctx, getAllBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.EventID,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
