// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: booking.sql

package sqlc_repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	bookingmodels "ticket-booking/internal/booking/models"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO booking (id, account_id, status, expires_at, paid_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, account_id, status, expires_at, paid_at, created_at
`

type CreateBookingParams struct {
	ID        uuid.UUID                   `json:"id"`
	AccountID uuid.UUID                   `json:"account_id"`
	Status    bookingmodels.BookingStatus `json:"status"`
	ExpiresAt *time.Time                  `json:"expires_at"`
	PaidAt    *time.Time                  `json:"paid_at"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.ID,
		arg.AccountID,
		arg.Status,
		arg.ExpiresAt,
		arg.PaidAt,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAllBookings = `-- name: GetAllBookings :many
SELECT id, account_id, status, expires_at, paid_at, created_at FROM booking
`

func (q *Queries) GetAllBookings(ctx context.Context) ([]Booking, error) {
	rows, err := q.db.Query(ctx, getAllBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Status,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
