// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event.sql

package sqlc_repository

import (
	"context"
	"time"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO event (title, description, location, starts_at, ends_at, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, description, starts_at, ends_at, location, status, created_at
`

type CreateEventParams struct {
	Title       string     `json:"title"`
	Description *string    `json:"description"`
	Location    string     `json:"location"`
	StartsAt    time.Time  `json:"starts_at"`
	EndsAt      *time.Time `json:"ends_at"`
	Status      string     `json:"status"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartsAt,
		arg.EndsAt,
		arg.Status,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.Location,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAllEvents = `-- name: GetAllEvents :many
SELECT id, title, description, starts_at, ends_at, location, status, created_at FROM event
`

func (q *Queries) GetAllEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, getAllEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.Location,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvent = `-- name: GetEvent :one
SELECT id, title, description, starts_at, ends_at, location, status, created_at FROM event
WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.Location,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
