// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_repository

import (
	"time"

	"ticket-booking/internal/user"
)

type Account struct {
	ID       int64     `json:"id"`
	Name     string    `json:"name"`
	Email    string    `json:"email"`
	Password string    `json:"password"`
	Role     user.Role `json:"role"`
}

type Booking struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	EventID   int64 `json:"event_id"`
	Quantity  int32 `json:"quantity"`
}

type Event struct {
	ID          int64      `json:"id"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	Date        *time.Time `json:"date"`
	Location    string     `json:"location"`
}

type RefreshToken struct {
	UserID     int64     `json:"user_id"`
	TokenHash  string    `json:"token_hash"`
	ExpiresAt  time.Time `json:"expires_at"`
	Revoked    bool      `json:"revoked"`
	ReplacedBy *int64    `json:"replaced_by"`
}

type Ticket struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int64  `json:"price"`
	Quantity    int32  `json:"quantity"`
	EventID     int64  `json:"event_id"`
}
