// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_repository

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"ticket-booking/internal/booking/models"
	"ticket-booking/internal/user/models"
)

type Account struct {
	ID        int64       `json:"id"`
	Name      string      `json:"name"`
	Email     string      `json:"email"`
	Password  string      `json:"password"`
	Role      models.Role `json:"role"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type Booking struct {
	ID        int64                `json:"id"`
	AccountID int64                `json:"account_id"`
	Status    models.BookingStatus `json:"status"`
	ExpiresAt *time.Time           `json:"expires_at"`
	PaidAt    *time.Time           `json:"paid_at"`
	CreatedAt time.Time            `json:"created_at"`
}

type BookingItem struct {
	ID             int64          `json:"id"`
	BookingID      int64          `json:"booking_id"`
	TicketTypeID   int64          `json:"ticket_type_id"`
	Quantity       int32          `json:"quantity"`
	PriceAtBooking pgtype.Numeric `json:"price_at_booking"`
}

type Event struct {
	ID          int64      `json:"id"`
	Title       string     `json:"title"`
	Description *string    `json:"description"`
	StartsAt    time.Time  `json:"starts_at"`
	EndsAt      *time.Time `json:"ends_at"`
	Location    string     `json:"location"`
	Status      string     `json:"status"`
	CreatedAt   time.Time  `json:"created_at"`
}

type RefreshToken struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"user_id"`
	TokenHash  string    `json:"token_hash"`
	ExpiresAt  time.Time `json:"expires_at"`
	Revoked    bool      `json:"revoked"`
	ReplacedBy *int64    `json:"replaced_by"`
	CreatedAt  time.Time `json:"created_at"`
}

type TicketType struct {
	ID                int64          `json:"id"`
	Name              string         `json:"name"`
	Description       *string        `json:"description"`
	Price             pgtype.Numeric `json:"price"`
	AvailableQuantity int32          `json:"available_quantity"`
	EventID           int64          `json:"event_id"`
	CreatedAt         time.Time      `json:"created_at"`
}
