// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: refresh_token.sql

package sqlc_repository

import (
	"context"
	"time"
)

const createToken = `-- name: CreateToken :one
INSERT INTO refresh_token (user_id, token_hash, expires_at, revoked)
VALUES ($1, $2, $3, $4)
RETURNING user_id, token_hash, expires_at, revoked
`

type CreateTokenParams struct {
	UserID    int64     `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	Revoked   bool      `json:"revoked"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Revoked,
	)
	var i RefreshToken
	err := row.Scan(
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const getAllTokens = `-- name: GetAllTokens :many
SELECT user_id, token_hash, expires_at, revoked FROM refresh_token
`

func (q *Queries) GetAllTokens(ctx context.Context) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, getAllTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshToken
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.UserID,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.Revoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTokenByUserID = `-- name: GetTokenByUserID :one
SELECT user_id, token_hash, expires_at, revoked FROM refresh_token
WHERE user_id = $1
`

func (q *Queries) GetTokenByUserID(ctx context.Context, userID int64) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getTokenByUserID, userID)
	var i RefreshToken
	err := row.Scan(
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const updateTokenByUserID = `-- name: UpdateTokenByUserID :exec
UPDATE refresh_token
SET token_hash = $2, expires_at = $3, revoked = $4 
WHERE user_id = $1
`

type UpdateTokenByUserIDParams struct {
	UserID    int64     `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	Revoked   bool      `json:"revoked"`
}

func (q *Queries) UpdateTokenByUserID(ctx context.Context, arg UpdateTokenByUserIDParams) error {
	_, err := q.db.Exec(ctx, updateTokenByUserID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Revoked,
	)
	return err
}
