// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_token.sql

package sqlc_repository

import (
	"context"
	"time"
)

const createToken = `-- name: CreateToken :one
INSERT INTO refresh_token (user_id, token_hash, expires_at, revoked, replaced_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, expires_at, revoked, replaced_by, created_at
`

type CreateTokenParams struct {
	UserID     int64     `json:"user_id"`
	TokenHash  string    `json:"token_hash"`
	ExpiresAt  time.Time `json:"expires_at"`
	Revoked    bool      `json:"revoked"`
	ReplacedBy *int64    `json:"replaced_by"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Revoked,
		arg.ReplacedBy,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.ReplacedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getAllTokens = `-- name: GetAllTokens :many
SELECT id, user_id, token_hash, expires_at, revoked, replaced_by, created_at FROM refresh_token
`

func (q *Queries) GetAllTokens(ctx context.Context) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, getAllTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshToken
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.Revoked,
			&i.ReplacedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT id, user_id, token_hash, expires_at, revoked, replaced_by, created_at FROM refresh_token
WHERE token_hash = $1
`

func (q *Queries) GetTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.ReplacedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getTokenByUserID = `-- name: GetTokenByUserID :one
SELECT id, user_id, token_hash, expires_at, revoked, replaced_by, created_at FROM refresh_token
WHERE user_id = $1
`

func (q *Queries) GetTokenByUserID(ctx context.Context, userID int64) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getTokenByUserID, userID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.ReplacedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateTokenByUserID = `-- name: UpdateTokenByUserID :one
UPDATE refresh_token
SET token_hash = $2, expires_at = $3, revoked = $4, replaced_by = $5
WHERE user_id = $1
RETURNING id, user_id, token_hash, expires_at, revoked, replaced_by, created_at
`

type UpdateTokenByUserIDParams struct {
	UserID     int64     `json:"user_id"`
	TokenHash  string    `json:"token_hash"`
	ExpiresAt  time.Time `json:"expires_at"`
	Revoked    bool      `json:"revoked"`
	ReplacedBy *int64    `json:"replaced_by"`
}

func (q *Queries) UpdateTokenByUserID(ctx context.Context, arg UpdateTokenByUserIDParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, updateTokenByUserID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Revoked,
		arg.ReplacedBy,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
		&i.ReplacedBy,
		&i.CreatedAt,
	)
	return i, err
}
