// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ticket.sql

package sqlc_repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO ticket_type (name, description, price, available_quantity, event_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, price, available_quantity, event_id, created_at
`

type CreateTicketParams struct {
	Name              string         `json:"name"`
	Description       *string        `json:"description"`
	Price             pgtype.Numeric `json:"price"`
	AvailableQuantity int32          `json:"available_quantity"`
	EventID           int64          `json:"event_id"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (TicketType, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.AvailableQuantity,
		arg.EventID,
	)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.AvailableQuantity,
		&i.EventID,
		&i.CreatedAt,
	)
	return i, err
}

const getAllTickets = `-- name: GetAllTickets :many
SELECT id, name, description, price, available_quantity, event_id, created_at FROM ticket_type
`

func (q *Queries) GetAllTickets(ctx context.Context) ([]TicketType, error) {
	rows, err := q.db.Query(ctx, getAllTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketType
	for rows.Next() {
		var i TicketType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.AvailableQuantity,
			&i.EventID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT ticket_type.id, ticket_type.name, ticket_type.description, ticket_type.price, ticket_type.available_quantity, ticket_type.event_id, ticket_type.created_at, event.id, event.title, event.description, event.starts_at, event.ends_at, event.location, event.status, event.created_at
FROM ticket_type
JOIN event ON event.id == ticket_type.event_id
WHERE ticket_type.id = $1
`

type GetTicketByIDRow struct {
	TicketType TicketType `json:"ticket_type"`
	Event      Event      `json:"event"`
}

func (q *Queries) GetTicketByID(ctx context.Context, id int64) (GetTicketByIDRow, error) {
	row := q.db.QueryRow(ctx, getTicketByID, id)
	var i GetTicketByIDRow
	err := row.Scan(
		&i.TicketType.ID,
		&i.TicketType.Name,
		&i.TicketType.Description,
		&i.TicketType.Price,
		&i.TicketType.AvailableQuantity,
		&i.TicketType.EventID,
		&i.TicketType.CreatedAt,
		&i.Event.ID,
		&i.Event.Title,
		&i.Event.Description,
		&i.Event.StartsAt,
		&i.Event.EndsAt,
		&i.Event.Location,
		&i.Event.Status,
		&i.Event.CreatedAt,
	)
	return i, err
}
