// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID    int32  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Booking struct {
	ID        int32       `json:"id"`
	AccountID pgtype.Int4 `json:"account_id"`
	EventID   pgtype.Int4 `json:"event_id"`
	Quantity  pgtype.Int4 `json:"quantity"`
}

type Event struct {
	ID          int32            `json:"id"`
	Title       string           `json:"title"`
	Description string           `json:"description"`
	Date        pgtype.Timestamp `json:"date"`
	Location    string           `json:"location"`
}

type Ticket struct {
	ID          int32         `json:"id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Price       pgtype.Float8 `json:"price"`
	Quantity    pgtype.Int4   `json:"quantity"`
	EventID     pgtype.Int4   `json:"event_id"`
}
