// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ticket.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO ticket (name, description, price, quantity, event_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, price, quantity, event_id
`

type CreateTicketParams struct {
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Price       pgtype.Float8 `json:"price"`
	Quantity    pgtype.Int4   `json:"quantity"`
	EventID     pgtype.Int4   `json:"event_id"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Quantity,
		arg.EventID,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Quantity,
		&i.EventID,
	)
	return i, err
}

const getAllTickets = `-- name: GetAllTickets :many
SELECT id, name, description, price, quantity, event_id FROM ticket
`

func (q *Queries) GetAllTickets(ctx context.Context) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, getAllTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Quantity,
			&i.EventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
