// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ticket.sql

package repository

import (
	"context"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO ticket (name, description, price, quantity, event_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, price, quantity, event_id
`

type CreateTicketParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       int64  `json:"price"`
	Quantity    int32  `json:"quantity"`
	EventID     int64  `json:"event_id"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Quantity,
		arg.EventID,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Quantity,
		&i.EventID,
	)
	return i, err
}

const getAllTickets = `-- name: GetAllTickets :many
SELECT id, name, description, price, quantity, event_id FROM ticket
`

func (q *Queries) GetAllTickets(ctx context.Context) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, getAllTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Quantity,
			&i.EventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicket = `-- name: GetTicket :one
SELECT ticket.id, ticket.name, ticket.description, ticket.price, ticket.quantity, ticket.event_id, event.id, event.title, event.description, event.date, event.location
FROM ticket
JOIN event ON event.id == ticket.event_id
WHERE ticket.id = $1
`

type GetTicketRow struct {
	Ticket Ticket `json:"ticket"`
	Event  Event  `json:"event"`
}

func (q *Queries) GetTicket(ctx context.Context, id int64) (GetTicketRow, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i GetTicketRow
	err := row.Scan(
		&i.Ticket.ID,
		&i.Ticket.Name,
		&i.Ticket.Description,
		&i.Ticket.Price,
		&i.Ticket.Quantity,
		&i.Ticket.EventID,
		&i.Event.ID,
		&i.Event.Title,
		&i.Event.Description,
		&i.Event.Date,
		&i.Event.Location,
	)
	return i, err
}
